config/routes.rb
Rails.application.routes.draw do


  resources :products, only: [:index], path: 'matos'
  resources :brands, only: :index, path: 'matos/marques'
  
  resources :brands , only: [:show], path: "matos/",  param: :name do  
    resources :products, only: :show, path: ':year/:model/'
  end

  #/brand/year/model

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products, dependent: :destroy
  mount_uploader :logo, PhotoUploader
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :product
  mount_uploader :photo, PhotoUploader
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  has_many :galleries
  has_many :sizes
  has_many :reviews
  has_many :user_gears, through: :sizes
  mount_uploader :photo, PhotoUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/size.rb
class Size < ApplicationRecord
  belongs_to :product
  has_many :user_gears
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  has_many :user_gears
end

app/models/user_gear.rb
class UserGear < ApplicationRecord
  belongs_to :size
  belongs_to :user
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @brands = policy_scope(Brand)
  end

  def show
    @brand = Brand.find_by(name: params[:name])
    authorize @brand

    @filters = @brand.products.distinct.pluck(:gear_type)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
    @products = policy_scope(Product)
  end

  def new
    @product = Product.new
    authorize @product
  end

  def show
    @product = Product.find(params[:id])
    authorize @product
  end

  def create

    product = Product.new(product_params)
    authorize product

    if product.save
      flash[:notice] = "Matos ajouté"
      redirect_to product_path
    else
      flash[:alert] = "Impossible de créer le matos"
      redirect_to products_path
    end

  end

  private

  def product_params
    params.require(:product).permit(:brand_id, :model, :gear_type, :year, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/brands/_brand_list.html.erb
<div class="listing-item mb-20">
  <div class="row grid-space-0">

    <div class="col-xs-4">
      <div class="overlay-container">
        <%= cl_image_tag brand.logo, style:'padding: 20px; max-height: 130px;'%>
      </div>
    </div>

    <div class="col-xs-8">
      <h3 class="margin-clear"><%= link_to brand.name, brand_path(brand.name) %></a></h3>
        <p>
          <i class="fa fa-star text-default"></i>
          <i class="fa fa-star text-default"></i>
          <i class="fa fa-star text-default"></i>
          <i class="fa fa-star text-default"></i>
          <i class="fa fa-star"></i>
        </p>
        <p><%= brand.description.first(300) + '...' %><a href="#" style="padding-left: 10px;">Plus de détails >></a></p>
        <div class="elements-list clearfix"></div>
    </div>

  </div>
</div>

app/views/brands/index.html.erb
<h1 class="page-title">Toutes les marques</h1>
<div class="separator-2"></div>
<div class="tab-content clear-style">
  <div class="tab-pane active" id="pill-1">
    <% @brands.each do |brand| %>
      <%= render 'brands/brand_list', brand: brand %>
      <div class="separator-3"></div>
    <% end %>
  </div>
</div>

app/views/brands/show.html.erb
<div class="main col-md-12">

  <!-- page-title start -->
  <!-- ================ -->
  <h1 class="page-title"><%= @brand.name %></h1>
  <div class="separator-2"></div>
  <!-- page-title end -->
  <p><%= @brand.description %></p>

  <!-- isotope filters start -->
  <div class="filters">
    <ul class="nav nav-pills">
      <li class="active"><a href="#" data-filter="*">Tout</a></li>
      <% @filters.each do |filter| %>
        <li><a href="#" data-filter=".<%= filter.gsub(' ', '-')%>"><%= filter %></a></li>
      <% end %>
    </ul>
  </div>
  <!-- isotope filters end -->

  <div class="isotope-container row grid-space-10" style="display: block; position: relative; height: 385.344px;">
    <% @brand.products.each do |product| %>
      <%= render 'shared/product2', product: product %>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Kitesurf Guide</title>

    <!-- THEME -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:700,400,300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=PT+Serif' rel='stylesheet' type='text/css'>

    <!-- <link href="/theme/bootstrap/css/bootstrap.css" rel="stylesheet"> -->
    <link href="/theme/fonts/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="/theme/fonts/fontello/css/fontello.css" rel="stylesheet">
    <link href="/theme/plugins/magnific-popup/magnific-popup.css" rel="stylesheet">
    <link href="/theme/plugins/rs-plugin-5/css/settings.css" rel="stylesheet">
    <link href="/theme/plugins/rs-plugin-5/css/layers.css" rel="stylesheet">
    <link href="/theme/plugins/rs-plugin-5/css/navigation.css" rel="stylesheet">
    <link href="/theme/css/animations.css" rel="stylesheet">
    <link href="/theme/plugins/owlcarousel2/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="/theme/plugins/owlcarousel2/assets/owl.theme.default.min.css" rel="stylesheet">
    <link href="/theme/plugins/hover/hover-min.css" rel="stylesheet">    
    <link href="/theme/css/style.css" rel="stylesheet" >
    <link href="/theme/css/skins/orange.css" rel="stylesheet">
    <link href="/theme/css/custom.css" rel="stylesheet">
    <!-- FIN THEME -->

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

  </head>
  <body>
    <%= render 'shared/scrolltop' %>

    <div class='page-wrapper'>
      <%= render 'shared/navbar' %>
      <section class='main-container'>
        <div class='container'>
          <div class='row'>
            <%= render 'shared/flashes' %>
            <%= yield %>
          </div>
        </div>
      </section>
      <%= yield :section %>
      <%= render 'shared/footer' %>
    </div>




    <%= javascript_include_tag 'application' %>
    <!-- THEME -->
    
    <!-- Modernizr javascript -->
    <script type="text/javascript" src="/theme/plugins/modernizr.js"></script>
    <script type="text/javascript" src="/theme/plugins/rs-plugin-5/js/jquery.themepunch.tools.min.js?rev=5.0"></script>
    <script type="text/javascript" src="/theme/plugins/rs-plugin-5/js/jquery.themepunch.revolution.min.js?rev=5.0"></script>
    <script type="text/javascript" src="/theme/plugins/rs-plugin-5/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script type="text/javascript" src="/theme/plugins/rs-plugin-5/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script type="text/javascript" src="/theme/plugins/rs-plugin-5/js/extensions/revolution.extension.navigation.min.js"></script>
    <!-- Isotope javascript -->
    <script type="text/javascript" src="/theme/plugins/isotope/isotope.pkgd.min.js"></script>
    <!-- Magnific Popup javascript -->
    <script type="text/javascript" src="/theme/plugins/magnific-popup/jquery.magnific-popup.min.js"></script>
    <!-- Appear javascript -->
    <script type="text/javascript" src="/theme/plugins/waypoints/jquery.waypoints.min.js"></script>
    <!-- Count To javascript -->
    <script type="text/javascript" src="/theme/plugins/jquery.countTo.js"></script>
    <!-- Parallax javascript -->
    <script src="/theme/plugins/jquery.parallax-1.1.3.js"></script>
    <!-- Contact form -->
    <script src="/theme/plugins/jquery.validate.js"></script>
    <!-- Background Video -->
    <script src="/theme/plugins/vide/jquery.vide.js"></script>
    <!-- Owl carousel javascript -->
    <script type="text/javascript" src="/theme/plugins/owlcarousel2/owl.carousel.min.js"></script>
    <!-- Initialization of Plugins -->
    <script type="text/javascript" src="/theme/js/template.js"></script>
    <!-- Custom Scripts -->
    <script type="text/javascript" src="/theme/js/custom.js"></script>
    <!-- FIN THEME -->
  </body>
</html>

app/views/pages/home.html.erb
home

app/views/products/index.html.erb
<h1 class="page-title">Tous les kites</h1>
<div class="separator-2"></div>
<%= render 'shared/products', products: @products %>

app/views/products/new.html.erb
<div class='container'>
  <%= simple_form_for @product, html: {id: "form-index"} do |f|%>
    <%= f.input :brand_id, collection: Brand.all, prompt: "Choisissez la marque" %>
    <%= f.input :model %>
    <%= f.input :year %>
    <%= f.input :gear_type, collection: ['Aile', 'Twin Tip', 'Surf', 'Foil', 'Harnais'], prompt: "Type de matos" %>
    <% # f.input :type, ['Aile', 'Twin Tip', 'Surf', 'Foil', 'Harnais'] %>
    <%= f.input :photo %>
    <%= f.submit %>
  <% end %>
</div>

app/views/products/show.html.erb
<!-- main start -->
<!-- ================ -->
<div class="main col-md-12">

  <!-- page-title start -->
  <!-- ================ -->
  <h1 class="page-title text-center"><%= @product.brand.name.capitalize %> <%= @product.model.capitalize %> <%= @product.year %></h1>
  <!-- page-title end -->

  <div class="row">
    <div class="col-md-4 col-lg-5">
      <!-- pills start -->
      <!-- ================ -->
      <!-- Nav tabs -->
      <ul class="nav nav-pills" role="tablist">
        <li class="active"><a href="#pill-1" role="tab" data-toggle="tab" title="images"><i class="fa fa-camera pr-5"></i> Photo</a></li>
        <li><a href="#pill-2" role="tab" data-toggle="tab" title="video"><i class="fa fa-video-camera pr-5"></i> Video</a></li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content clear-style">
        <div class="tab-pane active" id="pill-1">
          <div class="owl-carousel content-slider-with-thumbs mb-20">
            <div class="overlay-container overlay-visible">
              <%= cl_image_tag @product.photo.url(:main_caroussel) %>
              <a href="<%= cl_image_path @product.photo %>" class="owl-carousel--popup-img overlay-link"><i class="icon-plus-1"></i></a>
            </div>
            <% @product.galleries.each do |photo| %>
              <div class="overlay-container overlay-visible">
                <%= cl_image_tag photo.photo.url(:main_caroussel) %>
                <a href="<%= cl_image_path photo.photo %>" class="owl-carousel--popup-img overlay-link" ><i class="icon-plus-1"></i></a>
              </div>
            <% end %>
          </div>
          <% if !@product.galleries.empty? %>
            <div class="content-slider-thumbs-container">
              <div class="owl-carousel content-slider-thumbs">
                <div class="owl-nav-thumb">
                  <%= cl_image_tag @product.photo.url(:small_caroussel) %>
                </div>

                <% @product.galleries.each do |photo| %>
                  <div class="owl-nav-thumb">
                    <%= cl_image_tag photo.photo.url(:small_caroussel) %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="tab-pane" id="pill-2">
          <div class="embed-responsive embed-responsive-16by9">
            <%= @product.video.html_safe if @product.video %>
          </div>
        </div>
      </div>
      <!-- pills end -->
      <hr class="mb-10">
      <div class="clearfix mb-20">
        <span>
          <i class="fa fa-star text-default"></i>
          <i class="fa fa-star text-default"></i>
          <i class="fa fa-star text-default"></i>
          <i class="fa fa-star text-default"></i>
          <i class="fa fa-star"></i>
        </span>
        <a href="#" class="wishlist"><i class="fa fa-heart-o pl-10 pr-5"></i>Wishlist</a>
        <ul class="pl-20 pull-right social-links circle small clearfix margin-clear animated-effect-1">
          <li class="twitter"><a target="_blank" href="http://www.twitter.com"><i class="fa fa-twitter"></i></a></li>
          <li class="googleplus"><a target="_blank" href="http://plus.google.com"><i class="fa fa-google-plus"></i></a></li>
          <li class="facebook"><a target="_blank" href="http://www.facebook.com"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="col-md-8 col-lg-7 pv-30">
      <h2>Description</h2>
      <p><%= @product.description %></p>
      <h4 class="space-top">Specifications</h4>
      <hr>
      <dl class="dl-horizontal">
        <dt>Marque</dt>
        <dd><%= link_to @product.brand.name.capitalize, brand_path(@product.brand.name) %></dd>
        <dt>Model</dt>
        <dd><%= @product.model %></dd>
        <dt>Année</dt>
        <dd><%= @product.year %></dd>
        <dt>Tailles (m2)</dt>
        <dd>
          <% @product.sizes.each do |size_obj| %>
            <%= size_obj.size.to_s + ' /' %>
          <% end %>
        </dd>
        <dt>Programme</dt>
        <dd><%= @product.programme.capitalize %></dd>
        <dt>Niveau recommandé</dt>
        <dd><%= @product.min_level %> /3</dd>
      </dl>
    </div>
  </div>
</div>
<% content_for :section do %> 
  <%= render 'shared/reviews', product: @product %>
<% end %>
<!-- main end -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer" class="clearfix ">
  <!-- .footer start -->
  <!-- ================ -->
  <div class="footer">
    <div class="container">
      <div class="footer-inner">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="footer-content text-center padding-ver-clear">
              <div class="logo-footer"><img id="logo-footer" class="center-block" src="images/logo_brown.png" alt=""></div>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus illo vel dolorum soluta consectetur doloribus sit. Delectus non tenetur odit dicta vitae debitis suscipit doloribus. Lorem ipsum dolor sit amet, illo vel dolorum soluta consectetur.</p>
              <ul class="list-inline mb-20">
                <li><i class="text-default fa fa-map-marker pr-5"></i>One infinity loop, 54100</li>
                <li><a href="tel:+00 1234567890" class="link-dark"><i class="text-default fa fa-phone pl-10 pr-5"></i>+00 1234567890</a></li>
                <li><a href="mailto:info@theproject.com" class="link-dark"><i class="text-default fa fa-envelope-o pl-10 pr-5"></i>info@theproject.com</a></li>
              </ul>
              <ul class="social-links circle animated-effect-1 margin-clear">
                <li class="facebook"><a target="_blank" href="http://www.facebook.com"><i class="fa fa-facebook"></i></a></li>
                <li class="twitter"><a target="_blank" href="http://www.twitter.com"><i class="fa fa-twitter"></i></a></li>
                <li class="googleplus"><a target="_blank" href="http://plus.google.com"><i class="fa fa-google-plus"></i></a></li>
                <li class="linkedin"><a target="_blank" href="http://www.linkedin.com"><i class="fa fa-linkedin"></i></a></li>
                <li class="xing"><a target="_blank" href="http://www.xing.com"><i class="fa fa-xing"></i></a></li>
              </ul>
              <div class="separator"></div>
              <p class="text-center margin-clear">Copyright © 2017 The Project by <a target="_blank" href="http://htmlcoder.me">HtmlCoder</a>. All Rights Reserved</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- .footer end -->

</footer>

app/views/shared/_navbar.html.erb
<div class="header-container">
  <!-- header-top end -->

  <!-- header start -->
  <!-- classes:  -->
  <!-- "fixed": enables fixed navigation mode (sticky menu) e.g. class="header fixed clearfix" -->
  <!-- "dark": dark version of header e.g. class="header dark clearfix" -->
  <!-- "full-width": mandatory class for the full-width menu layout -->
  <!-- "centered": mandatory class for the centered logo layout -->
  <!-- ================ --> 
  <header class="header  fixed    clearfix animated object-visible fadeInDown">

    <div class="container">
      <div class="row">
        <div class="col-md-3 ">
          <!-- header-first start -->
          <!-- ================ -->
          <div class="header-first clearfix">

            <!-- header dropdown buttons -->
            <div class="header-dropdown-buttons visible-xs">
              <div class="btn-group dropdown">
                <button type="button" class="btn dropdown-toggle" data-toggle="dropdown"><i class="icon-search"></i></button>
                <ul class="dropdown-menu dropdown-menu-right dropdown-animation">
                  <li>
                    <form role="search" class="search-box margin-clear">
                      <div class="form-group has-feedback">
                        <input type="text" class="form-control" placeholder="Search">
                        <i class="icon-search form-control-feedback"></i>
                      </div>
                    </form>
                  </li>
                </ul>
              </div>
            </div>
            <!-- header dropdown buttons end-->

            <!-- logo -->
            <div id="logo" class="logo">
              <a href="index.html"><img id="logo_img" src="images/logo_light_blue.png" alt="Kitesurf Guide"></a>
            </div>

            <!-- name-and-slogan -->
            <div class="site-slogan">
              Partageons notre passion
            </div>

          </div>
          <!-- header-first end -->

        </div>
        <div class="col-md-9">

          <!-- header-second start -->
          <!-- ================ -->
          <div class="header-second clearfix">

            <!-- main-navigation start -->
            <!-- classes: -->
            <!-- "onclick": Makes the dropdowns open on click, this the default bootstrap behavior e.g. class="main-navigation onclick" -->
            <!-- "animated": Enables animations on dropdowns opening e.g. class="main-navigation animated" -->
            <!-- "with-dropdown-buttons": Mandatory class that adds extra space, to the main navigation, for the search and cart dropdowns -->
            <!-- ================ -->
            <div class="main-navigation  animated with-dropdown-buttons">

              <!-- navbar start -->
              <!-- ================ -->
              <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">

                  <!-- Toggle get grouped for better mobile display -->
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>

                  </div>

                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <div class="collapse navbar-collapse" id="navbar-collapse-1">
                    <!-- main-menu -->
                    <ul class="nav navbar-nav ">

                      <!-- mega-menu start -->
                      <li>
                        <%= link_to 'Home', root_path %>
                      </li>
                      <!-- mega-menu end -->
                      <!-- mega-menu start -->
                      <li>
                        <%= link_to 'Matos', products_path %>
                      </li> 
                      <li>
                        <%= link_to 'Marques', brands_path %>
                      </li>
                    </ul>
                    <!-- main-menu end -->
                    <!-- header dropdown buttons -->
                    <div class="header-dropdown-buttons hidden-xs ">
                      <div class="btn-group">
                        
                        <%= link_to new_user_session_path, class:'btn btn-default btn-sm' do %>
                          <i class="fa fa-user pr-10"></i></a>
                        <% end %>
                      </div>
                      <div class="btn-group dropdown">
                        <button type="button" class="btn dropdown-toggle btn-default btn-sm" data-toggle="dropdown"><i class="fa fa-lock pr-10"></i></button>
                        <ul class="dropdown-menu dropdown-menu-right dropdown-animation">
                          <li>
                            <form class="login-form margin-clear">
                              <div class="form-group has-feedback">
                                <label class="control-label">Username</label>
                                <input type="text" class="form-control" placeholder="">
                                <i class="fa fa-user form-control-feedback"></i>
                              </div>
                              <div class="form-group has-feedback">
                                <label class="control-label">Password</label>
                                <input type="password" class="form-control" placeholder="">
                                <i class="fa fa-lock form-control-feedback"></i>
                              </div>
                              <button type="submit" class="btn btn-gray btn-sm">Log In</button>
                              <span class="pl-5 pr-5">or</span>
                              <button type="submit" class="btn btn-default btn-sm">Sing Up</button>
                              <ul>
                                <li><a href="#">Forgot your password?</a></li>
                              </ul>
                              <span class="text-center">Login with</span>
                              <ul class="social-links circle small colored clearfix">
                                <li class="facebook"><a target="_blank" href="http://www.facebook.com"><i class="fa fa-facebook"></i></a></li>
                                <li class="twitter"><a target="_blank" href="http://www.twitter.com"><i class="fa fa-twitter"></i></a></li>
                                <li class="googleplus"><a target="_blank" href="http://plus.google.com"><i class="fa fa-google-plus"></i></a></li>
                              </ul>
                            </form>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <!-- header dropdown buttons end-->

                  </div>

                </div>
              </nav>
              <!-- navbar end -->

            </div>
            <!-- main-navigation end -->
          </div>
          <!-- header-second end -->

        </div>
      </div>
    </div>

  </header>
  <!-- header end -->
</div>

app/views/shared/_navbarWAGON.html.erb
<header>
  <div class="navbar-wagon">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">
    
      <%= link_to "Matos", products_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <% if user_signed_in? %>

        <!-- Links when logged in -->
        
        <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

        <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Some mobile link</a></li>
          <li><a href="#">Other one</a></li>
          <li><a href="#">Other one</a></li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_product.html.erb
<div class="image-box style-2 mb-20 shadow bordered light-gray-bg text-center">
  <div class="overlay-container">
    <%= cl_image_tag product.photo.url(:main_caroussel) %>
  </div>
  <div class="body">
    <%= link_to brand_product_path(product.brand.name, product.year, product.model, product) do %>
      <h3><%= product.brand.name.capitalize %> <%= product.model %> <%= product.year %></h3>               
    <% end %>
  </div>
</div>

app/views/shared/_product2.html.erb
<div class="col-md-3 col-sm-6 isotope-item <%= product.gear_type.gsub(' ', '-') %>" style="position: absolute; left: 288px; top: 0px;">
  <div class="image-box shadow bordered text-center mb-20">
    <div class="overlay-container">
      <%= cl_image_tag product.photo.url(:main_caroussel) %>
      <div class="overlay-top">
      </div>
      <div class="overlay-bottom">
        <h3>
          <%= link_to brand_product_path(product.brand.name, product.year, product.model, product) do%> 
            <%= product.model %> <%= product.year %>
          <% end %>
        </h3>
      </div>
    </div>
  </div>
</div>

app/views/shared/_products.html.erb
<div class='row'>
  <% products.each do |product| %>
    <div class='col-md-3 col-xs-6'>
      <%= render 'shared/product', product:product %>
    </div>
  <% end %>
</div>

app/views/shared/_ranking_stars.html.erb
<% 5.times do |i|  %>
  <%= rating - (i) > 0 ? '<i class="fa fa-star text-default"></i>'.html_safe : '<i class="fa fa-star"></i>'.html_safe %>
<%end %>